languageCode = "en-us"
title = "databae.io"
baseurl = "http://databae.io"
theme = "strange-case"


[params]
    colorScheme="scheme-slate"
    description = "helpful programming nuggets."
    sideBarFreeText = ""
    DateFormat = "2 Jan 2006"
